public class Demo {

		public static void func() {
			try {
				throw new Exception();
					//System.out.println("A");//编译错误,提示该语句无法访问,去掉后,结果为 B D
				} catch(Exception e)  {
					System.out.println("B");
				}
		}
		
		
		public static void main(String[] args) {
		try {
			func();
			
		} catch(Exception e) {
			System.out.println("C");//无作用（原因：func方法自身对抛出的异常进行处理了）
		} 
			System.out.println("D");
		}
}
